### ISSUE TITLE
Node now needs to handle rejection as well

### ISSUE THREAD

**Issue by shelldandy** [snaerth/create-react-component-folder#10]
https://github.com/snaerth/create-react-component-folder/blob/6830f6aa9f5315c0d766ad20ae85ee377d3227d3/lib/index.js#L66

<img width="921" alt="screen shot 2018-05-28 at 12 14 12 pm" src="https://user-images.githubusercontent.com/7088511/40624190-a55c9402-6270-11e8-8dab-ae471084db88.png">

Just my guess about why this is happenning now 😢

**Comment by snaerth** [comment]
I will take a look at it. Could you tell me your operating system?

**Comment by snaerth** [comment]
I can't reproduce this error. It is related to the prettier parser error in issue #11. So it should be fixed. Can you verify @shelldandy ?

**Comment by shelldandy** [comment]
all good now :D
