### ISSUE TITLE
Not working on 0.1.18

### ISSUE THREAD

**Issue by shelldandy** [snaerth/create-react-component-folder#11]
https://github.com/snaerth/create-react-component-folder/issues/10

<img width="921" alt="screen shot 2018-05-28 at 12 14 12 pm" src="https://user-images.githubusercontent.com/7088511/40624190-a55c9402-6270-11e8-8dab-ae471084db88.png">

That happens when running any command, maybe there's a dependency conflicting with `create-react-app` for that project at that state I just had `styled-components` installed besides `react-scripts`

🤔

**Comment by shelldandy** [comment]
Steps to reproduce:

```sh
npx create-react-app testing
```

⏲ ...

```sh
npm install --save-dev create-react-component-folder
```

⏲ ...

`package.json`

```json
{
  "name": "testing",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "create-react-component-folder": "^0.1.18"
  }
}
```

```sh
npx crcf src/components/Header
```

Picture above happens...

**Comment by shelldandy** [comment]
<img width="1911" alt="screen shot 2018-05-29 at 2 16 24 am" src="https://user-images.githubusercontent.com/7088511/40643610-546bf56c-62e6-11e8-956a-ffaa8650331b.png">

These warnings also popped when installing `crcf`

**Comment by shelldandy** [comment]
Bug not happenning before on ^0.1.17 🤔

**Comment by shelldandy** [comment]
Deleting yarn.lock, node_modules and installing again it finally works and it seems like cause of the bug is spelled in the console...

Going back to 0.1.17 

<img width="795" alt="screen shot 2018-05-29 at 3 11 06 am" src="https://user-images.githubusercontent.com/7088511/40646207-26193064-62ee-11e8-8265-b6854904e2f6.png">

**Comment by shelldandy** [comment]
Seems like `parser: 'babylon'` must be passed in the format.js options so everything continues to work without breaking:

https://github.com/snaerth/create-react-component-folder/blob/16c163fb617521ca9abddc3c723643aae237cce1/lib/utils/format.js#L7

https://prettier.io/docs/en/options.html#parser

**Comment by snaerth** [comment]
@shelldandy Hi and thank you for your tips. I just had a newborn, so I have little time on my hands. I will take a look at it hopefully today or this weekend. And I am of course always open to pull requests :)

**Comment by shelldandy** [comment]
Congratulations on your newborn! No problem at all, I've been working a bit on my fork to send the PR, this issue is a bit of a notebook for me as well to just dump the progress so far 😄

**Comment by snaerth** [comment]
Thank you so much :). I have fixed the prettier parser in version 0.1.20. Can you verify? @shelldandy

**Comment by shelldandy** [comment]
working fine now thanks a lot :)

**Comment by snaerth** [comment]
No thank you :)
