### ISSUE TITLE
Linting is failing

### ISSUE THREAD

**Issue by shelldandy** [snaerth/create-react-component-folder#12]
<img width="891" alt="screen shot 2018-05-29 at 1 23 49 pm" src="https://user-images.githubusercontent.com/7088511/40677545-9a0eaf9e-6343-11e8-837f-eb5ba5429a7f.png">

Should we keep those files not being used? Maybe it would be good to delete them to clean up console real estate.

🤔

**Comment by snaerth** [comment]
Thank you. Linting has been fixed in version 0.1.20
