### ISSUE TITLE
Option for JEST tests

### ISSUE THREAD

**Issue by flyfishMT** [snaerth/create-react-component-folder#16]
I'd like the MyComponent.test.[tsx/js] file to look like this if using Jest option rather than Enzyme. This seems to be the default when using create-react-app.

```
import React from 'react';
import ReactDOM from 'react-dom';
import MyComponent from './MyComponent';

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<MyComponent/>, div);
  ReactDOM.unmountComponentAtNode(div);
});
```

**Comment by bndnio** [comment]
Why was the PR to resolve this closed? I for one would love this functionality

**Comment by dragon-slayer** [comment]
Would also like functionality for RTL stubs instead of enzyme!

**Comment by Daveawb** [comment]
This is now possible in version `0.0.3` with `publish-templates`. You can modify the generated code per project to output exactly what you need.
