### ISSUE TITLE
Feature Request: No Semi Colons flag

### ISSUE THREAD

**Issue by samusgray** [snaerth/create-react-component-folder#19]
Thanks so freaking much for this tool! It is a huge time saver.

We use [Standard](https://standardjs.com) for out linting. I understand not everyone loves that, but we do! And many do. Would be nice to not need to remove each semicolon manually after creating a component.

```
npx crcf components/foo --nosemi
```

The result would be that each file is created, but without semicolons.

**Comment by snaerth** [comment]
@samusgray Hi and thank you for the compliment. I will definitely take a look at it very soon

**Comment by snaerth** [comment]
@samusgray No semicolon option has been added in v0.1.28. Thank you for a great tip

**Comment by samusgray** [comment]
Amazing! Thanks so much.
