### ISSUE TITLE
Add options [name].module.css for CSS modules

### ISSUE THREAD

**Issue by ojanh** [snaerth/create-react-component-folder#21]
Hi.
based on create-react-app docs, it can use css modules, but must create .module.css files to make it work. I hope there's an options to create file [component folder name].module.css files to make it easier.

thanks

**Comment by snaerth** [comment]
Hi and thanks for a great tip. I will add this feature soon!

**Comment by snaerth** [comment]
@ojanh The feature has been added in version 0.1.3v. You can now create the components with the option  --cssmodules
