### ISSUE TITLE
Option for default folder

### ISSUE THREAD

**Issue by silviopaganini** [snaerth/create-react-component-folder#22]
It's a bit annoying having to type `src/components/${Component}` every time... would be nice to put the option for the default folder

**Comment by snaerth** [comment]
Good idea. Yes, it possible to but it in the defaults. I will look into it soon

**Comment by Daveawb** [comment]
#24 would support this

**Comment by Daveawb** [comment]
@silviopaganini the PR was merged and you can now add a config option

```
package.json

{
   ...
   crcf: [
       {
            output: '/default/output/dir'
       }
   ]
```

**Comment by silviopaganini** [comment]
awesome!
