### ISSUE TITLE
Templates and other ideas (implemented in fork)

### ISSUE THREAD

**Issue by Daveawb** [snaerth/create-react-component-folder#24]
I had some requirements in a project recently that needed some finer control over the creation of the different components. I've got the working code in a fork https://github.com/Daveawb/create-react-component-folder.

I wondered if this would be of any use to you, it does add a dependency on handlebars to manage templates but abstracts a lot of logic away from the main index and creation scripts.

- Added a configuration `namedexports` to remove default exports and export named variables only.
- Added Typescript propTypes (removed {{name}}.propTypes) and added a TS type instead when typescript is in the configuration.
- Added Typescript types to functional components
- All options have default values that are passed in from cosmiconfig
- Run time configuration values are merged with the defaults to provide a consistent config array throughout the script.
- A minor configuration helper added to get items from a config store
- Templates are rendered using handlebars rather than JS. This could potentially allow for the templates to be published into a project allowing for finer control over how components etc. are rendered.
- Removed all the generation functions in favour of one `createReactComponent` function.

- Fixed ESLint and TSLint problems with current template layouts.

Let me know if this is of any use to you and I'll clean it up and put in a PR.

*Additional*

- Refactored config to use a global store with a frozen API that is available as a require in any script that needs it without passing it around in arguments.
    - Config is an object with two keys, `flags` and `values`, these are not directly accessible.
    - Config exposes a simple API to check, get and merge values.
- Added `--output <directory> | -o <directory>` to options to allow configuring default output location
- Cleaned up templates and fixed a few bugs with prop types

**Comment by Daveawb** [comment]
I've just also added an ability to publish templates to a project for modification.

**Comment by Daveawb** [comment]
With the modifications to the config, it should be relatively easy to allow values to be applied through arguments as well such as a root project directory for creation of components.

**Comment by snaerth** [comment]
This looks great. I will have a better look at it soon and let you know what I think, and then you could probably make an PR 👍

**Comment by Daveawb** [comment]
I just added a capability to adjust the output directory using default config.

either
`crcf MyComponent -o src // Outputs to  /src/MyComponent/{files}`

.crcfrc
```
[
   { output: 'src' },
   "typescrpt",
   ...
]
```

Or any other cosmiconfig location.

**Comment by snaerth** [comment]
For me, this isn't a big issue because. You can just do...

`crcf src/components/About Navigation Header Footer` 

and that will create four components ABout Navigation Header and Footer

**Comment by Daveawb** [comment]
It was less about the configuration option and more about the ability to set it by default. Specifically a project I'm working on right now has this `./public/toBuild/js/src/components` as it's route. Mildly insane but a reality that meant being able to add `{ output: './public/toBuild/js/src` }` to the config was very helpful.

**Comment by silviopaganini** [comment]
Any updates on this PR?

**Comment by Daveawb** [comment]
@silviopaganini Right now the fork does a lot more than I think @snaerth wants in the core package. I'm happy to strip it down but I need to know where @snaerth draws the line.

**Comment by snaerth** [comment]
Hi @silviopaganini . Sorry for the late reply I am officially back. I am open to any PR that will make this repo better. Keep the PR coming and I will review them asap :)

And I like this configure options it would be a nice addition to the repo

**Comment by Daveawb** [comment]
Ok, added the PR for you to review. #38
