### ISSUE TITLE
--createindex issues

### ISSUE THREAD

**Issue by niradler** [snaerth/create-react-component-folder#4]
- make default path to  /, 
currently using crcf --createindex will crash
 throw new TypeError('Path must be a string. Received ' + inspect(path));

- instead of 
export default {
change to 
export {

**Comment by snaerth** [comment]
@niradler I will take a look at it soon and fix it. Thank you

**Comment by niradler** [comment]
Cool, I'm here if you need anything. 

I was thinking how cool will it be to integrate the tool with vs code extension, do you know if it possible to add option to the right click menu in the file tree?

**Comment by Aidurber** [comment]
@niradler Yes it's possible, I use an extension called Move TS which allows me to move TS files and update imports in all relevant files. This is done via the context menu. 

https://github.com/stringham/move-ts

**Comment by snaerth** [comment]
@niradler I just made an patch to fix export default to export in createIndex. Thank for letting me know 👍 and feel free to make an pull request or more issues anytime :)
