### ISSUE TITLE
"notest" causes no test file AND no css file

### ISSUE THREAD

**Issue by maenthoven** [snaerth/create-react-component-folder#42]
This is my package.json:

`
  "crcf": [
    "typescript",
    "cssmodules",
    "scss",
    "notest",
    {
      "output": "src/"
    }
  ]
`

As a result, only the index.ts and component .tsx files are created

Removing the "notest" flag causes both the test foile AND the scss module to appear.

**Comment by Daveawb** [comment]
@maenthoven thanks for reporting this, I’ll take a look unless you fancy putting a PR yourself?

**Comment by maenthoven** [comment]
I wish I was a good enough programmer to be able to do that, @Daveawb :-P
