### ISSUE TITLE
react (web) component generated in react-native app

### ISSUE THREAD

**Issue by jimthedev** [snaerth/create-react-component-folder#5]
It looks like running `npx crcf components/Player` create a web react component (which has a div) instead of creating a React Native component. This yields the following error:

<img width="257" alt="screen shot 2018-04-15 at 8 55 20 am" src="https://user-images.githubusercontent.com/108938/38779214-fa17d630-408a-11e8-8545-16dfe0e97bdb.png">

**Comment by snaerth** [comment]
Create-react-component-folder defaults to web React component. When you are creating a React Native component you should type **npx crcf --reactnative components/Player**. You can also type "npx crcf --help" to list out options.
And it is on my todo list to be able to save default options so you don't have to add these parameters every time :)

**Comment by jimthedev** [comment]
Gotcha, I quick searched the readme but it looks like options is currently an image. For the purposes of being able to search it might be worth putting it into text. Cheers!
