### ISSUE TITLE
Prettier options aren't used by createMultiIndex fn

### ISSUE THREAD

**Issue by Jay-A-McBee** [snaerth/create-react-component-folder#54]
:wave: Hey @snaerth - thanks for all the work creating this lib. It makes scaffolding out a React cmp super fast 🚀 .  I noticed a small omission when it comes to prettier options. When I use the `createindex` option, my import file paths are always created using double-quotes even though my `.crcfrc` file contains 'singlequote'. 

The "prettier" options aren't pulled from the config and passed to the createMutiIndex fn - https://github.com/snaerth/create-react-component-folder/blob/master/lib/index.js#L206. 

`formatPrettier` ends up being called without any passed prettier options - https://github.com/snaerth/create-react-component-folder/blob/master/lib/utils/createMultiIndex.js#L28.  

The default prettier config is used - https://github.com/snaerth/create-react-component-folder/blob/master/lib/utils/format.js#L12

I'd be happy to put up a PR to add this to the createMultiIndex function.

**Comment by snaer-yolabs** [comment]
@Jay-A-McBee yes please that would be awesome

**Comment by Jay-A-McBee** [comment]
✅  I'll get something together in the next couple days
