### ISSUE TITLE
Suggestion: Set Defaults on package.json

### ISSUE THREAD

**Issue by shelldandy** [snaerth/create-react-component-folder#7]
Maybe something to read from package.json some defaults for example to leave the --reactnative option on or scss or something along those lines 🤔

**Comment by snaerth** [comment]
@shelldandy That's an good idea. It has been on my todo list to set default or save default. I hadn't thought to set a specific prop in package.json. This will be my next assignment. And I am always open to pull requests :)

**Comment by shelldandy** [comment]
Maybe even better could be with cosmiconfig (which is what eslint, stylelint etc use)

https://github.com/davidtheclark/cosmiconfig

```js
const cosmiconfig = require('cosmiconfig');
// ...
const explorer = cosmiconfig(moduleName);

// Search for a configuration by walking up directories.
// See documentation for search, below.
explorer.search()
  .then((result) => {
    // result.config is the parsed configuration object.
    // result.filepath is the path to the config file that was found.
    // result.isEmpty is true if there was nothing to parse in the config file.
  })
  .catch((error) => {
    // Do something constructive.
  });
```

**Comment by sicknarlo** [comment]
This PR could be what you're looking for https://github.com/snaerth/create-react-component-folder/pull/13

**Comment by snaerth** [comment]
This has now been merged into master with some minor fixes. So now you can set default config in .crcfrc / crcf.config.js or package.json. [https://github.com/snaerth/create-react-component-folder#set-default-config](url)
